Fix compilation error: rename lambda parameter from 'char' to 'character'
- 'char' is a reserved keyword in Java and cannot be used as variable name
- Renamed to 'character' to fix compilation errors